---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/crun.spec

srpm_build_deps:
  - git-archive-all
  - make
actions:
  create-archive:
    - "git-archive-all -v --force-submodules rpm/crun-HEAD.tar.xz"
    - bash -c "ls -1 rpm/crun-HEAD.tar.xz"

jobs:
  - job: copr_build
    trigger: pull_request
    # keep in sync with https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next
    targets:
      - fedora-all-x86_64
      - fedora-all-aarch64
      - fedora-eln-x86_64
      - fedora-eln-aarch64
      - centos-stream+epel-next-8-x86_64
      - centos-stream+epel-next-8-aarch64
      - centos-stream+epel-next-9-x86_64
      - centos-stream+epel-next-9-aarch64
    additional_repos:
      - "copr://rhcontainerbot/podman-next"

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    branch: main
    owner: rhcontainerbot
    project: podman-next

  - job: propose_downstream
    trigger: release
    update_release: false
    dist_git_branches:
      - fedora-all

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched # rawhide updates are created automatically
