matrix:
  allow_failures:
  - env: TEST=coverity
  - env: TEST=sonarcloud
cache:
  directories:
    - '$HOME/.sonar/cache'
env:
  matrix:
  - TEST=make
  - TEST=sonarcloud
  - TEST=podman
  - TEST=oci-validation
  - TEST=coverity
  global:
  - COVERITY_SCAN_PROJECT_NAME="giuseppe/crun"
  - COVERITY_SCAN_NOTIFICATION_EMAIL="giuseppe@scrivano.org"
  - COVERITY_SCAN_BRANCH_PATTERN="coverity|master"
  - COVERITY_SCAN_BUILD_COMMAND_PREPEND="./configure"
  - COVERITY_SCAN_BUILD_COMMAND="make coverity"
  - COVERITY_SCAN_BUILD_URL="https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh"
  - COVERITY_SCAN_BUILD="wget -qO- $COVERITY_SCAN_BUILD_URL | bash"
  - secure: "Psgi4JTzjdWoFeDp1nftwgACsbTtp6p5LdiTKP2/1q3JXR4qqNAFloxhQ+6MBRAK33JOkuskW9RyepPxOxcKf+9/n6MVcZE4t6vCKtxljpxOtPSsk1RGi4Vof8Zg3F28bSOft8QotEemwlO+Du142rC3uXp/xETciIrJRGkQGoDldFAxPee/RgpLn9RnRcOjT0gv0SLJu6JLvLhxOwktd3pSarWBffsCBoauQA4QFQTiDBd/c07DFgrN4jK1o/xLPSJ8J2w0a9H4ycyOyyfVlXM2vptB8rpxiHaIDV8xdxRUwJwwLeHE2fr7DofmwXpdbxoVqBZWji6sGslBJyRG1/xZAW+u1NKD1FcTmZtnvquXLMst4UG4mUPwC6egeuDfzvfsmFnqEAH9rivz8mKJGSrbWunpEF67aFZa9tVgHlUHw5Ei/9GT8fP6yzLNzXtQb//okX82CLY9TczlPFpP9l2Yp6AuW8cHIwX3JAD7rnFfaY2I6hCK+8059E4HvlHvYs9QAmmgh/6W9KTAlj5EZ5zPQaJEhOqcZCDtGdKk21lcRMBVu7NhV5hZiku8sAslf5TPdQ4ystiaVt6VR7cDvrAoYQxF2Bl24Fy/fylDXFzjP5T4kJNOWWDWywdEDanv3N9zM1Yo8oHJfrhduo+EU88MJNb3MjYU1AB0zKlEPv4="
services:
- docker
language: c
sudo: required
dist: xenial
addons:
  sonarcloud:
    organization: "giuseppe"
    token:
      secure: "cratZs866YzinJnsJvPpxGp+wGhp90Ei0uY8SM6p7ZAf0A0LGVFPUi+o2PeXRbjHLxqcjU4OvZdnz2/shYQh8ohEJxo9jH9HNM4j6O58O6vsk7/n4xzAzvnQK+1HKZ72Cz/fPLFDY8gwN2C+Ryq8nbqtzUohsiZNrtL3QFi9NerjgE8tTzod4YPrSHgpK8yaAAbuHxMkIZZO50Cf1lLCQPEjzMn2HJPCZgCOaOnh6hoP/+zAkwok8v/ZAEy0Fz63hBD/5OAYzdYYDtWVjDWoocGxxKMhlyIh+D5blUN4mLm4RyNIUi37puVhZT49Aua43GpdmiJ2iqCP8yF0OQHJ7eii2s53DwBQqtEdQIKG+ofoMmebgyPxTG7jxOD56h1ajNIXWOZ7/Ii3JuAGFCgRP/F7JC060hbj47CcqfUo4qqlfsw/18+X0pH7DBMzJl+JV0H7x6mbxJ30L3eZ4xUPF5dBNX7bcstXyuCQ+GkAA2PfalJMc4/50upeXVJ4ZhDkpPZ3xCxtJ71plcHH089l0KxgOdaCjerp19IoPx44Eo9otGRA/nO6YIPDHKAUJd5GZzSorguXGCzI4FEe/y9G5tDR2RsB+q7XXVE36f+PJtSVKMjB6sSFiQBk7270fXKUemQyDoo5YyjBp/rALtoHeyjfpP3WPBTeU33RroIzt98="
  apt:
    packages:
    - automake
    - autotools-dev
    - libseccomp-dev
    - git
    - make
    - libcap-dev
    - cmake
    - pkg-config
    - gcc
    - libseccomp-dev
    - libcap-dev
    - wget
    - go-md2man
before_install:
- sudo apt-get remove apparmor
- git submodule update --init --recursive
- if test $TEST = podman; then docker build -t crun-podman tests/podman; fi
- if test $TEST = oci-validation; then docker build -t crun-oci-validation tests/oci-validation;
  fi
- git clone --depth=1 git://github.com/lloyd/yajl
- "(cd yajl && ./configure -p /usr && make && sudo make install)"
script:
- if test $TEST = sonarcloud; then ./autogen.sh && build-wrapper-linux-x86-64 --out-dir bw-output sh -c './configure && make' && cd contrib/sonarcloud && sonar-scanner -X; fi
- if test $TEST = make; then ./autogen.sh && ./configure CFLAGS='-Wall -Werror' && make -j $(nproc) && make syntax-check; fi
- if test $TEST = podman; then sudo docker run --privileged --rm -ti -v /sys/fs/cgroup:/sys/fs/cgroup:rw,rslave -v $(pwd):/crun crun-podman; fi
- if test $TEST = oci-validation; then sudo docker run --privileged --rm -ti -v /sys/fs/cgroup:/sys/fs/cgroup:rw,rslave -v $(pwd):/crun crun-oci-validation; fi
- if test $TEST = coverity; then ./autogen.sh && eval "${COVERITY_SCAN_BUILD}"; fi
