env:
  - TEST=make
  - TEST=podman
  - TEST=oci-validation
services:
  - docker
language: c
sudo: required
dist: xenial
addons:
  apt:
    packages:
      - automake
      - autotools-dev
      - libseccomp-dev
      - git
      - make
      - libcap-dev
      - cmake
      - pkg-config
      - gcc
      - libseccomp-dev
before_install:
  - sudo apt-get remove apparmor
  - git submodule update --init --recursive
  - if test $TEST = podman; then docker build -t crun-podman tests/podman; fi
  - if test $TEST = oci-validation; then docker build -t crun-oci-validation tests/oci-validation; fi
  - git clone --depth=1 git://github.com/lloyd/yajl
  - (cd yajl && ./configure -p /usr && make && sudo make install)
script:
  - if test $TEST = make; then NOCONFIGURE=1 ./autogen.sh && ./configure CFLAGS='-Wall -Werror' && make -j $(nproc) && make syntax-check; fi
  - if test $TEST = podman; then sudo docker run --privileged --rm -ti -v /sys/fs/cgroup:/sys/fs/cgroup:rw,rslave -v $(pwd):/crun crun-podman; fi
  - if test $TEST = oci-validation; then sudo docker run --privileged --rm -ti -v /sys/fs/cgroup:/sys/fs/cgroup:rw,rslave -v $(pwd):/crun crun-oci-validation; fi
